### PR TITLE
Add Promise support

### PR DESCRIPTION
**Pull request by ignaczistvan**
When no callback is given we return a Promise on every async method in
Client.

### CODE REVIEW

**Comment by ignaczistvan** [comment]
Hm, bitHound is kind of right. Should I update the dev dependencies and add a .bithoundrc to ignore the generated docs?

**Comment by godong9** [comment]
@ignaczistvan 
Sorry, I'm late. Thanks your contribution.
Yes, Please update the dev dependencies and add a .bithoundrc to ignore the generated docs.

**Comment by ignaczistvan** [comment]
Hm, not much better. However I don't know if I should go further with these issues, because 
- gulp-mocha 4.0.1 requires node 4+
- I think the duplicated lines in the test files are OK.
- Fixing the issues in the query.js would mean a rewrite of that part

**Comment by godong9** [comment]
Thanks. I merged.

**Pull request merged**
