### PR TITLE
Add Suggest Component to use SOLR suggester

### PR DESCRIPTION
**Pull request by vb1704**
Added suggest function for client to query SOLR suggester

### CODE REVIEW

**Comment by vb1704** [comment]
@godong9 Please review this and merge if no issues, I have been using this module and had to adjust client file in order to use suggest component.

**Comment by lvenier** [comment]
Would be very nice to add it indeed.

@vb1704 : should you not add a unit test for suggester ?

**Comment by vb1704** [comment]
> Would be very nice to add it indeed.
> 
> @vb1704 : should you not add a unit test for suggester ?

Sure will add it!

**Comment by godong9** [comment]
Thanks to your contribution.
I will release this today.

**Pull request merged**
