### PR TITLE
add solr basic auth

### PR DESCRIPTION
**Pull request by lvenier**
Add optionnal user and password to solr client creation

### CODE REVIEW

**Comment by godong9** [comment]
This feature is breaking changes.
Need to consider backwards compatibility.

**Comment by lvenier** [comment]
Do you want me to check backwards compatibility and update the PR ?

**Comment by godong9** [comment]
Yes. Please check backwards compatibility and update.

**Comment by lvenier** [comment]
@godong9 : I have updated the Pr and fixed the backward compatibility.
pls review.

I think we should add 2 new unit test : 
- client option constructor with auth (user + password)
- make url with auth (user + password)

Opinion pls.

**Comment by godong9** [comment]
@lvenier 
Thanks to your contribution. 👍 
I agree your opinion that is need to 2 new unit test.
Please write unit test and update.

**Comment by lvenier** [comment]
@godong9  : 
You're welcome ! ;)

As discussed I have added 2 unit tests. Minimalist but doing the job.

Pls consider update README or doc with new user and password settings.

pls review.

**Comment by lvenier** [comment]
@godong9 : any comment ?

**Comment by godong9** [comment]
This is good.
I will release today.
Thanks. 👍

**Pull request merged**
